adding a reg type prop to Kinesis source
epiphanous/flinkrunner pull request #71
Opened 2023-03-15 23:53 UTC by LizaMo

This introduces a registration type property to the Kinesis source, with Lazy as default as per flink Kinesis implementation

2023-03-16 10:13 UTC, nextdude-mdsol requested changes
Do you know if this property solves your problem with running kinesis? It seems pretty specialized. My question is why add this property, while not adding other EFO properties, or other properties in general? It is possible to configure this without adding this specific property.  Also, we should have some tests to prove the configuration actually sets the value properly.

2023-03-16 10:13 UTC, nextdude-mdsol commented on src/main/scala/io/epiphanous/flinkrunner/model/source/KinesisSourceConfig.scala
> +    Seq("efo.registration.type", "flink.stream.efo.registration.type", EFO_REGISTRATION_TYPE),
Isn't `EFO_REGISTRATION_TYPE = "flink.stream.efo.regionstration.type"`? Don't need both.

2023-03-16 13:52 UTC, LizaMo commented on src/main/scala/io/epiphanous/flinkrunner/model/source/KinesisSourceConfig.scala
> +    Seq("efo.registration.type", "flink.stream.efo.registration.type", EFO_REGISTRATION_TYPE),
EFO_REGISTRATION_TYPE = "flink.stream.efo.registration"

2023-03-31 07:08 UTC, nextdude commented
We handled this a different way. Closing without merging.

2023-03-31 07:08 UTC, closed without merging